# Generated by Django 6.1 on 2026-08-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='creator',
            field=models.CharField(default='uploader', max_length=20),
            preserve_default=False,
        ),
    ]
