# Generated by Django 6.1 on 2026-08-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='title',
            field=models.CharField(default='社团简介', max_length=100),
            preserve_default=False,
        ),
    ]
