# Generated by Django 6.1 on 2026-08-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_index', '0002_intro_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
    ]
