# Generated by Django 6.1 on 2026-08-25 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_index', '0005_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'series'},
        ),
    ]
