# Generated by Django 6.1 on 2026-08-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_index', '0007_alter_activity_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('communication', models.TextField()),
            ],
        ),
    ]
