# Generated by Django 6.1 on 2026-08-25 05:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_series_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='bango',
            field=models.CharField(default='MAGI', max_length=20, validators=[django.core.validators.RegexValidator(message='只能输入英文字母和符号！', regex='^[a-zA-Z\\s_')]),
            preserve_default=False,
        ),
    ]
