# Generated by Django 6.1 on 2026-08-25 05:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_series_bango'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='bango',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='只能输入英文字母和符号！', regex='^[a-zA-Z_]+$')]),
        ),
    ]
