# Generated by Django 6.1 on 2026-08-25 05:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_series_bango'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='bango',
            field=models.CharField(error_messages={'unique': '该代号已经存在，请重新输入！'}, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='只能输入英文字母和下划线！', regex='^[a-zA-Z_]+$')]),
        ),
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(error_messages={'unique': '该名称已经存在，请重新输入！'}, max_length=100, unique=True),
        ),
    ]
