# Generated by Django 6.1 on 2026-08-26 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_owner_series_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='bango',
            field=models.CharField(blank=True, error_messages={'unique': '该代号已经存在，请重新输入！'}, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='只能输入英文字母和下划线！', regex='^[a-zA-Z_]+$')]),
        ),
    ]
