# Generated by Django 6.1 on 2026-08-26 12:57

import django.core.validators
from django.conf import settings
from django.db import migrations, models


def mark_existing_content_as_approved(apps, schema_editor):
    Series = apps.get_model('products', 'Series')
    Product = apps.get_model('products', 'Product')
    Series.objects.update(is_approved=True)
    Product.objects.update(is_approved=True)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_series_bango'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='已审核'),
        ),
        migrations.AddField(
            model_name='series',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='已审核'),
        ),
        migrations.AlterField(
            model_name='series',
            name='bango',
            field=models.CharField(blank=True, error_messages={'unique': '该代号已经存在，请重新输入！'}, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='只能输入英文字母和下划线！', regex='^[a-zA-Z_]+$')]),
        ),
        migrations.RunPython(
            mark_existing_content_as_approved,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='series',
            constraint=models.UniqueConstraint(condition=models.Q(('bango__isnull', False), models.Q(('bango', ''), _negated=True)), fields=('bango',), name='unique_nonempty_series_bango'),
        ),
        migrations.AddConstraint(
            model_name='series',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bango__isnull', False), ('is_approved', True), models.Q(('bango', ''), _negated=True)), models.Q(('is_approved', False), models.Q(('bango__isnull', True), ('bango', ''), _connector='OR')), _connector='OR'), name='series_approval_requires_bango'),
        ),
    ]
