# Generated by Django 6.1 on 2026-08-26 14:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_is_approved_series_is_approved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='series',
            name='series_approval_requires_bango',
        ),
        migrations.AddConstraint(
            model_name='series',
            constraint=models.CheckConstraint(condition=models.Q(('is_approved', False), models.Q(('bango__isnull', False), ('is_approved', True), models.Q(('bango', ''), _negated=True)), _connector='OR'), name='series_approval_requires_bango'),
        ),
    ]
