# Generated by Django 6.1 on 2026-08-28 08:39

import products.storage
import products.validators
import shutil
from pathlib import Path

from django.conf import settings
from django.db import migrations, models


def move_existing_product_files(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    public_root = Path(settings.MEDIA_ROOT)
    private_root = Path(settings.PRIVATE_MEDIA_ROOT)

    for product in Product.objects.exclude(file=''):
        file_name = str(product.file)
        source = public_root / file_name
        destination = private_root / file_name
        if source.exists() and not destination.exists():
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, destination)
        product.original_filename = Path(file_name).name
        product.save(update_fields=['original_filename'])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_series_series_approval_requires_bango_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='原始文件名'),
        ),
        migrations.RunPython(
            move_existing_product_files,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(storage=products.storage.PrivateProductStorage(), upload_to=products.validators.product_upload_path, validators=[products.validators.validate_product_file]),
        ),
    ]
