# Generated by Django 6.1 on 2026-08-30 08:38

import django.db.models.deletion
import hashlib
from pathlib import Path

from django.conf import settings
from django.db import migrations, models


def backfill_product_security_fields(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    private_root = Path(settings.PRIVATE_MEDIA_ROOT)
    for product in Product.objects.exclude(file=''):
        file_path = private_root / str(product.file)
        digest = hashlib.sha256()
        if file_path.exists():
            with file_path.open('rb') as product_file:
                for chunk in iter(lambda: product_file.read(1024 * 1024), b''):
                    digest.update(chunk)
            product.file_sha256 = digest.hexdigest()
            product.scan_status = 'clean' if product.is_approved else 'pending'
        else:
            product.scan_status = 'error'
        product.save(update_fields=['file_sha256', 'scan_status'])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_public_product_file_copies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file_sha256',
            field=models.CharField(blank=True, max_length=64, verbose_name='文件 SHA-256'),
        ),
        migrations.AddField(
            model_name='product',
            name='scan_status',
            field=models.CharField(choices=[('pending', '等待扫描'), ('clean', '扫描通过'), ('infected', '发现风险'), ('error', '扫描失败')], default='pending', max_length=20, verbose_name='扫描状态'),
        ),
        migrations.AddField(
            model_name='product',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='扫描时间'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='操作')),
                ('model_name', models.CharField(max_length=50, verbose_name='模型')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='对象 ID')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='详情')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.RunPython(
            backfill_product_security_fields,
            migrations.RunPython.noop,
        ),
    ]
